# AppVeyor script for wxSQLite3

# branches to build
branches:
  only:
    - master

# environments
environment:
  matrix:
  - TOOLSET: msbuild
    CONFIGURATION: Release wxDLL
    ARCH: x64
#  - TOOLSET: cmake
#    GENERATOR: 'Visual Studio 14.1'
#    SHARED: ON
#    CONFIGURATION: Release

# clone directory
clone_folder: c:\projects\wxsqlite3

# scripts to run before build
before_build:
  # set environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_x64_ReleaseDLL.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_x64_ReleasePDB.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxWidgets-3.1.2-headers.7z'
  - cmd: 7z x wxMSW-3.1.2_vc141_x64_Dev.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.2_vc141_x64_ReleaseDLL.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.2_vc141_x64_ReleasePDB.7z -oC:\wxWidgets
  - cmd: 7z x wxWidgets-3.1.2-headers.7z -oC:\wxWidgets

# build script
build_script: c:\projects\wxsqlite3\admin\appveyor\appveyor.bat
