# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp
sudo: required

matrix:
    include:
        - dist: trusty
          compiler: gcc
          env: WXGTK_PACKAGE=libwxgtk2.8-dev
        - dist: trusty
          compiler: gcc
          env: WXGTK_PACKAGE=libwxgtk3.0-dev
        - os: osx
          compiler: clang
          env: CXXFLAGS=-Wno-potentially-evaluated-expression

branches:
    only:
        - master

before_install:
    - ./admin/travis/before_install.sh
    - autoreconf

script:
    - set -e && echo 'Configuring...' && echo -en 'travis_fold:start:script.configure\\r'
    - ./configure
    - echo -en 'travis_fold:end:script.configure\\r'
    - echo 'Building...' && echo -en 'travis_fold:start:script.build\\r'
    - make
    - echo -en 'travis_fold:end:script.build\\r'
    - echo 'Installing...' && echo -en 'travis_fold:start:script.install\\r'
    - sudo make install
    - set +e && echo -en 'travis_fold:end:script.install\\r'

# The "set +e" is a workaround for https://github.com/travis-ci/travis-ci/issues/6522

